### ISSUE TITLE
benchmarks seem to be broken

### ISSUE THREAD

**Issue by rishavs** [itsumura-h/nim-basolato#111]
Hi

I wanted to check out the basolato benchmarks, but in techempower many benchmarks are just not working https://www.techempower.com/benchmarks/#section=test&runid=9716e3cd-9e53-433c-b6c5-d2c48c9593c1&hw=ph&test=fortune&a=2
and where they are working, the performance is unexpectedly low (specially for something using httpbeast ^_^). something is clearly not working there.

**Comment by itsumura-h** [comment]
@rishavs 
Yes! I'm trying fix test and update framework itself.
Here is a test result run in my personal environment. 
https://www.techempower.com/benchmarks/#section=test&shareid=cd2b6475-fa6c-4eb5-892b-a61306d9417e&hw=ph&test=plaintext&a=2

About performance, the first cause is sync database access. I fixed it only for PostgreSQL. (https://github.com/itsumura-h/nim-allographer/blob/master/src/allographer/async/asyncpg.nim)
The second is running single thread with async. I'm trying to make it able to run multi threads reference to httpbeast.

**Comment by itsumura-h** [comment]
solved

https://github.com/TechEmpower/FrameworkBenchmarks/pull/8662
