### ISSUE TITLE
How to set hostname ?

### ISSUE THREAD

**Issue by waghanza** [itsumura-h/nim-basolato#136]
Hi @itsumura-h,

How can we set hostname on basolato ?

It the last step to fix benchmarks in https://github.com/the-benchmarker/web-frameworks/pull/3683

Regards,

**Comment by itsumura-h** [comment]
@waghanza 
Updated v.0.9.0!
Now you can set hostname in `.env`
https://github.com/itsumura-h/nim-basolato/blob/master/documents/en/settings.md#host-string--0000

**Comment by waghanza** [comment]
seems it's time to reintroduce  in https://github.com/the-benchmarker/web-frameworks, then

**Comment by waghanza** [comment]
want to PR @itsumura-h ?

**Comment by itsumura-h** [comment]
https://github.com/the-benchmarker/web-frameworks/pull/5484
