### ISSUE TITLE
Cannot find the path specified

### ISSUE THREAD

**Issue by bhaswanth53** [itsumura-h/nim-basolato#140]
I am trying to create a new project named "demo" using ducere new demo command. But it is creating folder and showing some error like below.

The system cannot find the path specified.
Additional info: "(\"F:\\\\Technologies\\\\NIM\\\\Projects/demo/tmp/0.8/app\", \"F:\\\\Technologies\\\\NIM\\\\Projects/demo/app\")"

![image](https://user-images.githubusercontent.com/19569771/107033609-93cb3900-67db-11eb-953e-9e9b8d201299.png)

I am new to NIM, and I can't able to understand why this error occurs and how to fix it. Any help regarding this issue will be appreciated.

**Comment by itsumura-h** [comment]
@bhaswanth53 
I'm sorry for my response is too late.
It seem that the cause is running in Windows. The path system of Windows and Linux is different.
Please consider to use Docker if it is possible.
