### ISSUE TITLE
Fedora is assumed as Alpine

### ISSUE THREAD

**Issue by rikusen0335** [itsumura-h/nim-basolato#155]
## Describe the bug
When try `ducere serve`, outputs `/path/to/home/.asdf/installs/nim/1.4.8/nimble/pkgs/basolato-0.9.1/basolato/core/utils.nim(36, 27) Error: cannot open file: /lib/apk/db/installed`

`ducere serve`を実行したときに、`/path/to/home/.asdf/installs/nim/1.4.8/nimble/pkgs/basolato-0.9.1/basolato/core/utils.nim(36, 27) Error: cannot open file: /lib/apk/db/installed`が表示される

## Steps to reproduce
In Fedora 34, type `ducere serve`

Fedora 34で、`ducere serve`を実行する

## Expected behavior
`ldconfig -p | grep libsass` would executed instead

`ldconfig -p | grep libsass`が代わりに実行される

## Screenshots
![image](https://user-images.githubusercontent.com/19174234/119694216-fed27580-be87-11eb-8530-3d2a5e9b8604.png)

## Additional context
`nim` -> 1.4.8
`basolato` -> 0.9.1

`cat /etc/os-release` results:

```
NAME=Fedora
VERSION="34 (Workstation Edition)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/34/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

^ As you can see, `ID` specifies it's `fedora` (from reading source code)

^ `ID`が`fedora`になってることがわかると思います。

**Comment by rikusen0335** [comment]
As I wanted to clearfy: I installed `libsass` to the machine.

一応確認のため書きますが、`libsass`自体はすでにインストールしています！

**Comment by itsumura-h** [comment]
@rikusen0335 
ここでOSの判別しているんですよね
https://github.com/itsumura-h/nim-basolato/blob/master/src/basolato/core/utils.nim#L26-L34

なんでAlpineと認識されるのか謎です…

**Comment by teroz** [comment]
Hi there I got the exact same issue using `Ubuntu 20.04.2 LTS` and nim 1.4.8

![2021-08-06_14-46](https://user-images.githubusercontent.com/853846/128506066-b563c951-abb1-4d54-93ce-44eee7eb0f96.png)

**Comment by itsumura-h** [comment]
@rikusen0335 
恐らくlibsass側の問題だと思います
https://github.com/dom96/sass

単体で動くか試してみて下さい
```nim
import sass

let css = compile("body { div { color: red; } }")
echo css
```

**Comment by itsumura-h** [comment]
@teroz 
It is working

```
cat /etc/os-release 


NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
ldconfig -p | grep libsass


        libsass.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libsass.so.1
        libsass.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libsass.so
```

and recommended to use Docker

**Comment by teroz** [comment]
:clap:  :clap: :clap:
