### ISSUE TITLE
Warning on `nimble install https://github.com/itsumura-h/nim-basolato`

### ISSUE THREAD

**Issue by tarunama** [itsumura-h/nim-basolato#168]
### summary
Show below warning when execute `nimble install https://github.com/itsumura-h/nim-basolato`.
Important warning is `This will be an error in the future`.

```bash
 Warning: Package 'flatdb' has an incorrect structure. The top level of the package source directory should contain at most one module, named 'flatdb.nim', but a file named 'flatdbtable.nim' was found. This will be an error in the future.

Hint: If this is the primary source file in the package, rename it to 'flatdb.nim'. If it's a source file required by the main module, or if it is one of several modules exposed by 'flatdb', then move it into a 'flatdb/' subdirectory. If it's a test file or otherwise not required to build the the package 'flatdb.nim', prevent its installation by adding `skipFiles = @["flatdbtable.nim"]` to the .nimble file. See https://github.com/nim-lang/nimble#libraries for more info.
```

### solution
Rename `flatdb` => `flatdb.nim`

But, It was concerned that existing codes written `import flatdb` in many files.
So, above solution will breaks existing codes.

@itsumura-h 
How do you think?

### ref
https://github.com/juancarlospaco/nim_packages_security_audit/blob/7914f50b18d94d4969d1fb301f2310446e09434f/f/flatdb.log#L82

**Comment by itsumura-h** [comment]
@tarunama 
This warning occurs because of `flatdb` itself, so there is nothing I can do for `basolato`.
Please create issue for flatdb.
https://github.com/enthus1ast/flatdb

**Comment by tarunama** [comment]
@itsumura-h 
Thank you!
