### ISSUE TITLE
Segfault on high concurrency

### ISSUE THREAD

**Issue by waghanza** [itsumura-h/nim-basolato#245]
Hi @itsumura-h,

When I run `basolato` (https://github.com/the-benchmarker/web-frameworks/blob/master/nim/basolato/server.nim) inside a container
```dockerfile
FROM nimlang/nim:1.6.8-alpine
RUN apk update && \
    apk upgrade --no-cache
  RUN apk --no-cache add gcc
  RUN apk --no-cache add musl-dev
  RUN apk --no-cache add bsd-compat-headers
  RUN apk --no-cache add openssl
  RUN apk --no-cache add openssh-client
  RUN apk --no-cache add pcre-dev
WORKDIR /usr/src/app
COPY . ./
ENV PATH $PATH:/root/.nimble/bin
RUN nimble install -y
RUN nim c  -d:ssl --threads:on --threadAnalysis:off --gc:orc --putenv:PORT=3000  \
    --excessiveStackTrace:off \
    -d:release \
    --passC:-flto \
    --passL:-flto \
    server.nim
FROM alpine
RUN apk --no-cache add pcre-dev
COPY --from=0 /usr/src/app/server /usr/src/app/server
CMD /usr/src/app/server
```
I'm sometimes having 
```nim 
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault
```
when stressing the server with _wrk -H 'Connection: keep-alive' --connections 16 --threads 1 --duration 1 --timeout 1 http://localhost:3000_

In general, decrease the concurrency level (`connections` option) does not lead to the same behavior.

That's why `basolato` is failing in https://web-frameworks-benchmark.netlify.app/result?f=basolato

Regards,

**Comment by cpbotha** [comment]
I just had a quick look, and it seems that basolato currently relies on multi-processing and not multi-threading.

If you use the `ducere` tool to do your production build, it builds with `--threads:off` and it creates a `startServer.sh` where it
starts up as many server processes as you have cores on the build machine. (see example below)

Furthermore, when I look at the basolato techempower benchmark implementation here https://github.com/itsumura-h/nim-basolato/tree/c8fb05fbc4ed078f770509b0c47e9b585234f8ab/examples/benchmark/FrameworkBenchmarks/basolato it looks like they are running with a single process.

```
➜  ~/build/web-frameworks/nim/basolato git:(master) ✗ ducere build
    nim c \
     \
     \
    --threads: off \
    --gc:orc \
    -d:ssl \
    -d:danger \
    -d:release \
    --parallelBuild:0 \
    --passC:"-flto"\
    --passL:"-flto" \
    --panics: on \
    --stackTrace \
    --lineTrace \
    --putenv:PORT=5000 \
    --out: main \
    main.nim
...
```

Could you perhaps make the time to run your benchmark with `--threads:off`

**Comment by waghanza** [comment]
Hi @cpbotha,

I'm not very familiar with `nim` and `ducere`, but I have tried to change compilation options

###### Before

```nim
nim c  -d:ssl --threads:on --threadAnalysis:off --gc:orc --putenv:PORT=3000  \
    --excessiveStackTrace:off \
    -d:release \
    --passC:-flto \
    --passL:-flto \
    server.nim
```

###### After

```nim
nim c  -d:ssl --threads:off --threadAnalysis:off --gc:orc --putenv:PORT=3000  \
    --excessiveStackTrace:off \
    -d:release \
    --passC:-flto \
    --passL:-flto \
    server.nim
```

After reading some docs (about `ducere`), seems that `basolato` is compiled with `asynchttpserver`  by default, which is not **production-ready**, and probably not designed for the kind of usage I have

Could I provide an option to `nim c` to make sure `httpbeast` or `httpx` is used ?

**Comment by waghanza** [comment]
PS : Seems to work with `httpbeast`, I'll update results on the above benchmark on `monday`

**Comment by waghanza** [comment]
With the following compilation lines

```
nim c  --threads: off --gc:orc -d:ssl -d:danger --panics:on --stackTrace --lineTrace --putenv:PORT=3000 -d:httpbeast --parallelBuild:0  \
    --excessiveStackTrace:off \
    -d:release \
    --passC:-flto \
    --passL:-flto \
    server.nim
```

I can have the following stack

```nim
Traceback (most recent call last)
server.nim(14)           server
server.nim(116)          serve
httpbeast.nim(546)       run
httpbeast.nim(378)       eventLoop
httpbeast.nim(285)       processEvents
asyncmacro.nim(232)      cd
asyncmacro.nim(28)       cdNimAsyncContinue
server.nim(54)           cdIter
asyncmacro.nim(232)      new
asyncmacro.nim(31)       newNimAsyncContinue
context.nim(21)          newIter
asyncmacro.nim(232)      genNewSession
asyncmacro.nim(28)       genNewSessionNimAsyncContinue
session.nim(16)          genNewSessionIter
asyncmacro.nim(232)      new
asyncmacro.nim(28)       newNimAsyncContinue
session_db.nim(21)       newIter
asyncmacro.nim(232)      new
asyncmacro.nim(31)       newNimAsyncContinue
file_session_db.nim(111) newIter
flatdb.nim(149)          load
flatdbtable.nim(34)      add
lists.nim(988)           append
lists.nim(585)           add
lists.nim(157)           add
arc.nim(63)              nimDecRefIsLastCyclicStatic
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault (core dumped)
```

Maybe it can help @cpbotha @itsumura-h ?

**Comment by cpbotha** [comment]
Dear @waghanza thank you for continuing with this!

I am just an interested bystander who has spent some time with some of the nim web frameworks.

Why don't you want to try with the default `asynchttpserver`? It looks like that's what @itsumura-h used for his techempower benchmarks.

(Just BTW looking at the stack trace, there is still a super unexpected illegal memory access -- it looks like it's in the ORC cycle detection, so you could try changing `--gc:orc` to `--gc:arc` -- although that will probably only sidestep the actual root cause)

**Comment by waghanza** [comment]
Hi @cpbotha,

> I am just an interested bystander who has spent some time with some of the nim web frameworks.

I'm personally interested in how frameworks compares from each others :-)

> Why don't you want to try with the default asynchttpserver?
As I read the official doc, https://nim-lang.org/docs/asynchttpserver.html, seems that this part of nim's std has no intention to be **production-ready**, like https://werkzeug.palletsprojects.com/en/2.2.x/ in `python`.

As such I think something more like `httpbeast` (or else) should be used, no opinion about `httpx`. 

The results of a benchmark is more accurate if this reflect some production state (at least the project above)

Regards,

PS : I'll try `arc` and keep you posted, perhaps even `arc` should be used, I don't know, for the others nim frameworks on the above projects

**Comment by cpbotha** [comment]
> > Why don't you want to try with the default asynchttpserver?
> 
> As I read the official doc, https://nim-lang.org/docs/asynchttpserver.html, seems that this part of nim's std has no intention to be **production-ready**, like https://werkzeug.palletsprojects.com/en/2.2.x/ in `python`

To be fair, that part of the docs goes on to say the following:

> This HTTP server has not been designed to be used in production, but for testing applications locally. Because of this, when *deploying your application in production you should use a reverse proxy* (for example nginx) instead of allowing users to connect directly to this server.

They're not saying not to use it in prod, they're saying if you do, put a reverse proxy in front of it, something that for example many established and performant Python frameworks, such as uvicorn, also say.

**Comment by waghanza** [comment]
Sure. That's the long answer. 

However, in case of a benchmark (at least for this one), we do not put a reverse proxy (except for some php framework that could not listen to http directly) because it has a maintenance cost and it could mess the result at some point.

That's why I think we should not use it. 

Moreover, we have `scorper`, `akane`, `whip`, `prologue` ... I'm not sure it is accurate to compare those one with `asynchttpserver`

**Comment by cpbotha** [comment]
It's your benchmark. :)

... but purely because this is an interesting discussion I would like to add:

- akane seems to use asynchttpserver as well see https://github.com/Ethosa/akane/blob/master/akane/akane.nim#L5
- whip documentation: "WHIP is still in development and is not recommended for production use"
- prologue: defaults to httpbeast, but supports asynchttpserver with a single switch
- basolato seems to have a working implementation for all techempower benchmark sections, something that almost no other nim framework has

**Comment by waghanza** [comment]
maybe better to use the default, and rely on the framework itself to be **production-ready**. I mean using only `putenv`

if `akane` (example) use `asynchttpserver` should be that this framework **SHOULD** be used behind a reverse proxy, which I'm not sure @Ethosa 

in consequence using only the required option that need for this project could be relevant, following this discussion

but the command taken for the minimun need (`ducere build --port=30001) seems to work
```
nim c  --threads:off --gc:arc -d:danger --parallelBuild:0 --panics:on --stackTrace --lineTrace --putenv:PORT=3000   \
    --excessiveStackTrace:off \
    -d:release \
    --passC:-flto \
    --passL:-flto \
    server.nim
```
(only the gc is changed) => probably the failure is due to env => local docker (in this case should rather keep it as is and see what happens when changing of architecture, I mean having a test with a client and a server instead of a server for both)

**Comment by itsumura-h** [comment]
Hi.

You can use `httpbeast` or `httpx` instead of `asynchttpserver`. but for my environment, asynchttpserver has better perfomence than httpbeast or httpx. 
https://github.com/itsumura-h/nim-basolato/blob/main/documents/en/ducere.md#build

I reccomend to use `basolato` behind Nginx as official documents says in production. however to focus on performance of web frameworks, I think web server like `Nginx` or `Apatch` can removed from benchmark.

In web application, I think `ORC` is better to use than `ARC` because `ARC` cannot collect memory garbage in cycle reference.
Cycle reference often happen when application has `async` program.

I got the same segmentation fault many times. In latest version `0.14.1`, I think you can run application safety.
```sh
ducere build -p 3000
./startServer.sh
```
Maybe database connection can be the cause of error. Please check connection count to database. `num of process` * `num of db connection` should be smaller than db max connection.

**Comment by waghanza** [comment]
Thanks for follow up @itsumura-h 

I managed to have this compilation mode with
```dockerfile
FROM nimlang/nim:1.6.8-alpine

RUN apk update && \
    apk upgrade --no-cache

  RUN apk --no-cache add gcc
  RUN apk --no-cache add musl-dev
  RUN apk --no-cache add bsd-compat-headers
  RUN apk --no-cache add openssl
  RUN apk --no-cache add openssh-client
  RUN apk --no-cache add pcre-dev

WORKDIR /usr/src/app

COPY . ./

ENV PATH $PATH:/root/.nimble/bin

RUN nimble install -y

  RUN ducere build -p 3000

FROM alpine
WORKDIR /usr/src/app
RUN apk --no-cache add \
      pcre-dev openssl-dev

  COPY --from=0 /usr/src/app/main /usr/src/app/main
  COPY --from=0 /usr/src/app/startServer.sh /usr/src/app/startServer.sh

  CMD ./startServer.sh
```

but unfortunately I had

```
/usr/src/app # Traceback (most recent call last)
main.nim(14)             main
server.nim(125)          serve
asyncdispatch.nim(1956)  runForever
asyncdispatch.nim(1653)  poll
asyncdispatch.nim(1394)  runOnce
asyncdispatch.nim(234)   processPendingCallbacks
asyncmacro.nim(31)       processRequestNimAsyncContinue
asynchttpserver.nim(330) processRequestIter
asyncmacro.nim(232)      cb
asyncmacro.nim(31)       cbNimAsyncContinue
server.nim(89)           cbIter
logger.nim(31)           echoErrorMsg
io.nim(323)              close
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Traceback (most recent call last)
main.nim(14)             main
server.nim(125)          serve
asyncdispatch.nim(1956)  runForever
asyncdispatch.nim(1653)  poll
asyncdispatch.nim(1394)  runOnce
asyncdispatch.nim(234)   processPendingCallbacks
asyncmacro.nim(31)       processRequestNimAsyncContinue
asynchttpserver.nim(330) processRequestIter
asyncmacro.nim(232)      cb
asyncmacro.nim(31)       cbNimAsyncContinue
server.nim(90)           cbIter
logger.nim(31)           echoErrorMsg
io.nim(323)              close
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

> Maybe database connection can be the cause of error. Please check connection count to database. num of process * num of db connection should be smaller than db max connection.

Do you mean max connection handled by database server ?

**Comment by itsumura-h** [comment]
@waghanza 
Could you give me your onworking github repository and branch url?

**Comment by waghanza** [comment]
sure @itsumura-h 

I run `basolato` from a container (running on a single machine : CPUx8) defined by
```dockerfile
FROM nimlang/nim:1.6.8-alpine
RUN apk update && \
    apk upgrade --no-cache
RUN apk --no-cache add gcc
RUN apk --no-cache add musl-dev
RUN apk --no-cache add bsd-compat-headers
RUN apk --no-cache add openssl
RUN apk --no-cache add openssh-client
RUN apk --no-cache add pcre-dev
WORKDIR /usr/src/app
COPY . ./
ENV PATH $PATH:/root/.nimble/bin
RUN nimble install -y
RUN ducere build -p 3000
FROM alpine
WORKDIR /usr/src/app
RUN apk update && \
    apk upgrade --no-cache
RUN apk --no-cache add openssl-dev pcre-dev
COPY --from=0 /usr/src/app/main /usr/src/app/main
COPY --from=0 /usr/src/app/startServer.sh /usr/src/app/startServer.sh
CMD ./startServer.sh
```
and with the following command (outside the container) :
```
wrk -H 'Connection: keep-alive' --connections 8 --threads 8 --duration 8 --timeout 1 http://172.17.0.2:3000
```

I have

```
Running 8s test @ http://172.17.0.2:3000
  8 threads and 8 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.74ms    3.46ms  34.34ms   94.11%
    Req/Sec   221.74    127.36   848.00     75.40%
  13897 requests in 8.01s, 4.32MB read
  Socket errors: connect 0, read 13, write 0, timeout 0
  Non-2xx or 3xx responses: 13878
Requests/sec:   1735.48
Transfer/sec:    552.43KB
```

and on the container

```
/usr/src/app # ./startServer.sh
running 8 processes
Basolato based on asynchttpserver listening on 0.0.0.0:3000
Basolato based on asynchttpserver listening on 0.0.0.0:3000
Basolato based on asynchttpserver listening on 0.0.0.0:3000
Basolato based on asynchttpserver listening on 0.0.0.0:3000
Basolato based on asynchttpserver listening on 0.0.0.0:3000
Basolato based on asynchttpserver listening on 0.0.0.0:3000
Basolato based on asynchttpserver listening on 0.0.0.0:3000
Basolato based on asynchttpserver listening on 0.0.0.0:3000
Traceback (most recent call last)
main.nim(14)             main
server.nim(125)          serve
asyncdispatch.nim(1956)  runForever
asyncdispatch.nim(1653)  poll
asyncdispatch.nim(1394)  runOnce
asyncdispatch.nim(234)   processPendingCallbacks
asyncmacro.nim(31)       processRequestNimAsyncContinue
asynchttpserver.nim(330) processRequestIter
asyncmacro.nim(232)      cb
asyncmacro.nim(31)       cbNimAsyncContinue
server.nim(89)           cbIter
logger.nim(31)           echoErrorMsg
io.nim(323)              close
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Traceback (most recent call last)
main.nim(14)             main
server.nim(125)          serve
asyncdispatch.nim(1956)  runForever
asyncdispatch.nim(1653)  poll
asyncdispatch.nim(1394)  runOnce
asyncdispatch.nim(234)   processPendingCallbacks
asyncmacro.nim(31)       processRequestNimAsyncContinue
asynchttpserver.nim(330) processRequestIter
asyncmacro.nim(232)      cb
asyncmacro.nim(31)       cbNimAsyncContinue
server.nim(90)           cbIter
logger.nim(31)           echoErrorMsg
io.nim(323)              close
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Traceback (most recent call last)
main.nim(14)             main
server.nim(125)          serve
asyncdispatch.nim(1956)  runForever
asyncdispatch.nim(1653)  poll
asyncdispatch.nim(1394)  runOnce
asyncdispatch.nim(234)   processPendingCallbacks
asyncmacro.nim(31)       processRequestNimAsyncContinue
asynchttpserver.nim(330) processRequestIter
asyncmacro.nim(232)      cb
asyncmacro.nim(31)       cbNimAsyncContinue
server.nim(90)           cbIter
logger.nim(31)           echoErrorMsg
io.nim(323)              close
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Traceback (most recent call last)
main.nim(14)             main
server.nim(125)          serve
asyncdispatch.nim(1956)  runForever
asyncdispatch.nim(1653)  poll
asyncdispatch.nim(1394)  runOnce
asyncdispatch.nim(234)   processPendingCallbacks
asyncmacro.nim(31)       processRequestNimAsyncContinue
asynchttpserver.nim(330) processRequestIter
asyncmacro.nim(232)      cb
asyncmacro.nim(31)       cbNimAsyncContinue
server.nim(89)           cbIter
logger.nim(31)           echoErrorMsg
io.nim(323)              close
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Traceback (most recent call last)
main.nim(14)             main
server.nim(125)          serve
asyncdispatch.nim(1956)  runForever
asyncdispatch.nim(1653)  poll
asyncdispatch.nim(1394)  runOnce
asyncdispatch.nim(234)   processPendingCallbacks
asyncmacro.nim(31)       processRequestNimAsyncContinue
asynchttpserver.nim(330) processRequestIter
asyncmacro.nim(232)      cb
asyncmacro.nim(31)       cbNimAsyncContinue
server.nim(89)           cbIter
logger.nim(31)           echoErrorMsg
io.nim(323)              close
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Traceback (most recent call last)
main.nim(14)             main
server.nim(125)          serve
asyncdispatch.nim(1956)  runForever
asyncdispatch.nim(1653)  poll
asyncdispatch.nim(1394)  runOnce
asyncdispatch.nim(234)   processPendingCallbacks
asyncmacro.nim(31)       processRequestNimAsyncContinue
asynchttpserver.nim(330) processRequestIter
asyncmacro.nim(232)      cb
asyncmacro.nim(31)       cbNimAsyncContinue
server.nim(90)           cbIter
logger.nim(31)           echoErrorMsg
io.nim(323)              close
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

All code is accessible in https://github.com/the-benchmarker/web-frameworks/tree/basolato/nim/basolato (except for `Dockerfile` which is generated)

**Comment by waghanza** [comment]
not sure why but latest version of `nim` (https://nim-lang.org/blog/2022/11/23/version-1610-released.html) solved it @itsumura-h @cpbotha 

but I have with `wrk -H 'Connection: keep-alive' --connections 64 --threads 8 --duration 15 --timeout 1 --script /home/waghanza/workspace/benchmark/web/pipeline.lua http://172.17.0.2:3000/`

the following result

```
"OUT : Running 15s test @ http://172.17.0.2:3000/\n" +
"  8 threads and 64 connections\n" +
"  Thread Stats   Avg      Stdev     Max   +/- Stdev\n" +
"    Latency    86.72ms   48.59ms 971.60ms   96.41%\n" +
"    Req/Sec    97.09     26.66   333.00     83.60%\n" +
"  11365 requests in 15.02s, 3.53MB read\n" +
"  Socket errors: connect 0, read 0, write 0, timeout 12\n" +
"  Non-2xx or 3xx responses: 11365\n" +
"Requests/sec:    756.46\n" +
"Transfer/sec:    240.83KB\n"
```

**Comment by itsumura-h** [comment]
@waghanza 
I got the same error. It seems that the error only happen in 2nd stage of docker multi stage build. I don't know the reason why...

This can be run successfully

```docker
FROM nimlang/nim:1.6.10-alpine
RUN apk update && \
    apk upgrade --no-cache
RUN apk --no-cache add gcc
RUN apk --no-cache add musl-dev
RUN apk --no-cache add bsd-compat-headers
RUN apk --no-cache add openssl
RUN apk --no-cache add openssh-client
RUN apk --no-cache add pcre-dev
WORKDIR /usr/src/app
COPY . ./
ENV PATH $PATH:/root/.nimble/bin
RUN nimble install -y
RUN ducere build -p 3000
CMD ./startServer.sh
```

**Comment by itsumura-h** [comment]
@waghanza 
I found the solution. You need to take .env from stage 1st to 2nd.

Maybe the default value of environment variable is the cause of error.

Please add this.

```dickerfile
COPY --from=0 /usr/src/app/.env /usr/src/app/.env
```

**Comment by waghanza** [comment]
it works. thanks @itsumura-h @cpbotha 

with `wrk -H 'Connection: keep-alive' --connections 64 --threads 8 --duration 15 --timeout 1 --script /home/waghanza/workspace/benchmark/web/pipeline.lua http://172.17.0.2:3000/`

I have now
```
" Running 15s test @ http://172.17.0.2:3000/\n" +
"  8 threads and 64 connections\n" +
"  Thread Stats   Avg      Stdev     Max   +/- Stdev\n" +
"    Latency     2.37ms  619.17us  17.65ms   61.80%\n" +
"    Req/Sec     3.38k   432.14    11.72k    87.27%\n" +
"  404427 requests in 15.10s, 62.10MB read\n" +
"Requests/sec:  26783.04\n" +
"Transfer/sec:      4.11MB\n"
```

**Comment by waghanza** [comment]
will not it be better if `.env` was compile inside the binary @itsumura-h ? I mean it can allow to inject some per-environment variables, and the compile for different targets
