### ISSUE TITLE
Proposal: tests should not depends on user directory, such as /home/www

### ISSUE THREAD

**Issue by kubo39** [itsumura-h/nim-basolato#26]
Some people may not want to create new user for tests.

**Comment by itsumura-h** [comment]
@kubo39 
Developing framework assume using Docker and `/home/www` directory is created by Dockerfile. Also, `runTest.sh` is only used not develop web application but to develop framework itself.
However, I can change working directory under `/root`. Do you think it is a better way ?

**Comment by kubo39** [comment]
@itsumura-h 
Thank you for the response!

> Developing framework assume using Docker and /home/www directory is created by Dockerfile. Also, runTest.sh is only used not develop web application but to develop framework itself.

Uh-oh, I didn't notice that, wil try it later.

> However, I can change working directory under /root. Do you think it is a better way ?

I think it would not be so.
