### ISSUE TITLE
Web framework benchmark

### ISSUE THREAD

**Issue by waghanza** [itsumura-h/nim-basolato#73]
Hi @itsumura-h ,

Do you want to add `Basolato` in https://github.com/the-benchmarker/web-frameworks ?

The purpose of this benchmark is to compare frameworks on a simple (an homogeneous) way.

We have already :

+ `jester`
+ `httpbeast`

Wdyt ?

Regards,

**Comment by itsumura-h** [comment]
@waghanza 
I'd like it. Actually, I love to look the result of web framework benchmark comparison.
I want to add `Basolato` not only that git repository, but also here https://github.com/TechEmpower/FrameworkBenchmarks

**Comment by waghanza** [comment]
Relocated in https://github.com/the-benchmarker/web-frameworks (in order to pollute the issue list `here`)

Thanks :tada: again for your approval @itsumura-h

**Comment by itsumura-h** [comment]
If this issue is closed, I will forget lol

**Comment by itsumura-h** [comment]
submitted

https://github.com/TechEmpower/FrameworkBenchmarks/pull/5902
https://github.com/the-benchmarker/web-frameworks/pull/3181
