### ISSUE TITLE
ducere new でエラー

### ISSUE THREAD

**Issue by JanFish** [itsumura-h/nim-basolato#76]
日本語で失礼します。
ducere newで、ディレクトリがないとエラーが出力されました。
ソースをみたところ
nim-basolato-templates
のディレクトリ構成が変更されたため、発生しているようです。
(tmp/MCVディレクトリがtmp/DDDに変更など）

ご確認ください。

**Comment by mikebelanger** [comment]
I'm already using allographer, and this full-stack framework has got me excited!
But yes, I believe JanFish is correct, the changing  directory structure from MVC -> DDD hasn't been reflected in `newImpl.nim`.  That, and the `../tmp/app` directory was first moved, but the ensuing commands kept referencing that `../tmp/app`.

Not a big deal, I guess you're in the process of changing things anyways.  But in case you haven't tried this already, changing the directory move structure to 
```
    # get from tmp/MVC
    moveDir(&"{dirpath}/tmp/DDD/app", &"{dirpath}/app")
    moveDir(&"{dirpath}/app/middlewares", &"{dirpath}/middlewares")
    moveDir(&"{dirpath}/tmp/DDD/migrations", &"{dirpath}/migrations")
    moveDir(&"{dirpath}/tmp/DDD/public", &"{dirpath}/public")
    moveDir(&"{dirpath}/tmp/DDD/resources", &"{dirpath}/resources")
    moveFile(&"{dirpath}/tmp/DDD/main.nim", &"{dirpath}/main.nim")
    
    # move static file
    moveFile(&"{dirpath}/tmp/assets/basolato.svg", &"{dirpath}/public/basolato.svg")
    moveFile(&"{dirpath}/tmp/assets/favicon.ico", &"{dirpath}/public/favicon.ico")
    # remove tmp
    removeDir(&"{dirpath}/tmp")
```
Worked for me.  I was able to successfully create a project.


can't wait to see where this goes.

**Comment by itsumura-h** [comment]
@JanFish 
今バージョン0.4に上げ、newコマンドでのエラーは解消されていると思います。
まだ開発中のため、今後も破壊的変更が予測されるためご注意ください…

@mikebelanger 
The latest version solve this problem.
